analytics: {}
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
opengraph: {}
color:
  saturation: 0.38125034933909774
  brandStrength: 0.2892434543464333
  lightness: 0.08904427313245833
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
  rhythmicContrast: 0.7969226143322885
typography_spectrum: 0.9664552677422762
layout_spectrum: 0.21614547609351575
cta: {}
name: justme
