layout_spectrum: 0.7840340156108141
typography_spectrum: 0.13048236048780382
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.7323356743436307
  lightness: 0.9516018882859498
  saturation: 0.53362353798002
  rhythmicContrast: 0.3422825885936618
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: justme
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Back to One Earth Community '
    url: 'https://thegrid.ai/one-earth-community/'
    type: external
  - name: login
    url: 'https://testing.thegrid.io/app'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: Me and You
purpose: []
