analytics: {}
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
opengraph: {}
color:
  saturation: 0.8048818502575159
  brandStrength: 0.0750075492542237
  lightness: 0.20188207644969225
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  rhythmicContrast: 0.8725461619906127
typography_spectrum: 0.025081219617277384
layout_spectrum: 0.21614547609351575
cta: {}
name: justme
