favicon: null
name: justme
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.622449
  brandStrength: 0
  lightness: 0.604189
  brandColors:
    - '#081422'
    - '#FFFFFF'
    - '#C1AF9B'
    - '#796F65'
    - '#CB0672'
  rhythmicContrast: 0.1844208
typography_spectrum: 0.9522269
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2819549
analytics:
  twitter: null
  google: null
  facebook: null
