analytics: {}
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
opengraph: {}
color:
  saturation: 0.5798753954004496
  brandStrength: 0.32805652474053204
  lightness: 0.8933781469240785
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
  rhythmicContrast: 0.2027571266517043
typography_spectrum: 0.636849345639348
layout_spectrum: 0.3201082698069513
cta: {}
name: justme
