name: justme
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
opengraph: {}
color:
  saturation: 0.5902256
  brandStrength: 0
  lightness: 0.7083781
  brandColors:
    - '#081422'
    - '#FFFFFF'
    - '#C1AF9B'
    - '#796F65'
    - '#CB0672'
  rhythmicContrast: 0.1844208
typography_spectrum: 0.9522269
cta: {}
analytics: {}
layout_spectrum: 0
