layout_spectrum: 0.1642357788514346
typography_spectrum: 0.12984203919768333
color:
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
  brandStrength: 0.46961465687491
  lightness: 0.034882970387116075
  saturation: 0.04430274572223425
  rhythmicContrast: 0.6712554786354303
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/04bc7ac0-3191-421e-bbe8-b004d2a10c65.png
name: justme
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Back to One Earth Community '
    url: 'https://thegrid.ai/one-earth-community/'
    type: external
  - name: login
    url: 'https://testing.thegrid.io/app'
    type: external
  - name: my photos
    url: 'http://www.one-earthcommunity.photography/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/36aab223-517e-42b8-976b-e3c4adb85256.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: ''
purpose: []
