name: justme
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
opengraph: {}
color:
  saturation: 0.5902256
  brandStrength: 0.7599356
  lightness: 0.5580022
  brandColors:
    - '#020101'
    - '#FDC300'
    - '#E3470F'
    - '#633F41'
    - '#3B8B56'
  rhythmicContrast: 0.1745435
typography_spectrum: 0.9522269
layout_spectrum: 0
cta: {}
analytics: {}
