analytics: {}
color:
  brandColors:
    - '#081422'
    - '#FFFFFF'
    - '#C1AF9B'
    - '#796F65'
    - '#CB0672'
  brandStrength: 0
  lightness: 0.8834586
  rhythmicContrast: 0.1844208
  saturation: 0.5902256
cta: {}
layout_spectrum: 0.872122
name: justme
opengraph: {}
purpose: []
typography_spectrum: 0.9522269
